version: '3.4'

services:
  app:
    container_name: journey-app
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=JourneyDB;User Id=sa;Password=journey_db"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=CertPassword"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - db
    networks:
      - journey-network

  db:
    container_name: journey-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: journey_db
      POSTGRES_DB: JourneyDB
    ports:
      - 5432:5432
    networks:
      - journey-network

networks:
  journey-network:
    driver: bridge